windowrule = workspace 1, match:class ^(kitty)$
windowrule = workspace 2, match:class ^(firefox)$
windowrule = workspace 2, match:class ^(qutebrowser)$
# windowrule = workspace 3, match:class ^(dev\.zed\.Zed)$
# windowrule = workspace 3, match:class ^(codium)$
# windowrule = workspace 4, match:class ^(obsidian)$
# windowrule = workspace 5, match:class ^(thunar)$
# windowrule = workspace 8, match:class ^(discord)$
